---
- name: install ntp
  yum: name=ntp state=installed
  sudo: yes

- name: start ntpd
  service: name=ntpd state=started enabled=yes
  sudo: yes

- name: stop iptables
  service: name={{ item }} state=stopped
  sudo: yes
  with_items:
    - iptables
    - ip6tables

- name: include task for page files
  include: page_files.yml

- name: include task for config files
  include: config_files.yml
